### ISSUE TITLE
Duplicated regions in bed file

### ISSUE THREAD

**Issue by giacuong171** [bihealth/ngs-chew#37]
Hi,
while testing ngs-chew, I found out that there are some duplicated regions in bed files (GRCh38_sites and GRCh38_sitesX). As a result, the sites dictionary in the function snps_step_call and the result array in the function load_sites have different lengths, leading to an indexing error in the function roh.write_vcf. 
Duplicated regions are 10:50099997 on GRCh38_sites and {'X:22116210', 'X:54800636', 'X:44935923', 'X:70354079', 'X:67273789', 'X:47342919', 'X:118604435', 'X:52891583', 'X:10491232', 'X:118709566'} on GRCh38_sitesX.

**Comment by ericblanc20** [comment]
Fixed by https://github.com/bihealth/ngs-chew/pull/39
